# Working with NumPy
## Brandon Boyle
### Version 1
#### CS-150

In [1]:
import numpy as np

In [2]:
x1=np.array([[10, 20], [30, 40]])

In [3]:
x1

array([[10, 20],
       [30, 40]])

In [4]:
x1**2

array([[ 100,  400],
       [ 900, 1600]])

In [5]:
x1*5

array([[ 50, 100],
       [150, 200]])

In [12]:
np.sqrt(x1)

array([[3.16227766, 4.47213595],
       [5.47722558, 6.32455532]])

In [18]:
x2=np.arange(3,30,3).reshape(3,3)

In [19]:
x2

array([[ 3,  6,  9],
       [12, 15, 18],
       [21, 24, 27]])

In [24]:
x3=np.linspace(10,20,9).reshape(3,3)

In [25]:
x3


array([[10.  , 11.25, 12.5 ],
       [13.75, 15.  , 16.25],
       [17.5 , 18.75, 20.  ]])

In [26]:
x2*x3

array([[ 30. ,  67.5, 112.5],
       [165. , 225. , 292.5],
       [367.5, 450. , 540. ]])

In [32]:
y1=np.load('process1.npy')
y2=np.load('process2.npy')
y3=np.load('process3.npy')
y4=np.load('process4.npy')
y5=np.load('process5.npy')

In [40]:
z1=np.vstack([y1,y2,y3,y4,y5])

In [41]:
z1

array([[52, 12, 81,  0, 58],
       [96,  4, 61, 16, 43],
       [38, 96, 45, 17, 58],
       [97, 21, 22, 25,  6],
       [77,  6, 19,  2, 74]], dtype=int32)

In [43]:
np.mean(z1, axis=0)

array([72. , 27.8, 45.6, 12. , 47.8])